### ISSUE TITLE
Can't get the plugin to Work

### ISSUE THREAD

**Issue by MaxLinWorm** [Liu233w/wox-raindrop#1]
Hi, 

For the life of me I can't get this plugin to work.

I downloaded the full zip file.

Extracted it to `C:\Users\{USER}\AppData\Local\Wox\{app version}\Plugins\Wox.Plugin.Raindrop

Changed line 13 of main.py from:
```TEST_TOKEN = environ.get('RAINDROP_TOKEN') or ''```

to

```TEST_TOKEN = '{testtoken}'```

Whenever I activate the `rd` keyword, Wox just opens the cmd, and opens the plugin folder over and over.

Tried manually choosing the PYTHON path in Wox settings, no difference.

Using Wox v. 1.3.578, Python 3.9, Windows 11

AFAIK, python is working (HelloWorldPython plugin works)

This is the error log:

Sun, 26 Jun 2022 16:24:53 woxex.py[line:29] ERROR Traceback (most recent call last):
  File "C:\Users\Max Lin Worm\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Raindrop\woxex.py", line 35, in load_module
    yield
  File "C:\Users\Max Lin Worm\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Raindrop\main.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Sun, 26 Jun 2022 16:24:54 woxex.py[line:29] ERROR Traceback (most recent call last):
  File "C:\Users\Max Lin Worm\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Raindrop\woxex.py", line 45, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Max Lin Worm\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Raindrop\main.py", line 25, in request
    return requests.get(url, params=params, headers=headers)
NameError: name 'requests' is not defined

Sun, 26 Jun 2022 16:24:55 woxex.py[line:29] ERROR Traceback (most recent call last):
  File "C:\Users\Max Lin Worm\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Raindrop\woxex.py", line 45, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Max Lin Worm\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Raindrop\main.py", line 31, in query
    r = self.request('https://api.raindrop.io/rest/v1/raindrops/0', params={
AttributeError: 'NoneType' object has no attribute 'json'

Sun, 26 Jun 2022 16:51:19 woxex.py[line:29] ERROR Traceback (most recent call last):
  File "C:\Users\Max Lin Worm\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Raindrop\woxex.py", line 35, in load_module
    yield
  File "C:\Users\Max Lin Worm\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Raindrop\main.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Sun, 26 Jun 2022 16:51:20 woxex.py[line:29] ERROR Traceback (most recent call last):
  File "C:\Users\Max Lin Worm\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Raindrop\woxex.py", line 35, in load_module
    yield
  File "C:\Users\Max Lin Worm\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Raindrop\main.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Sun, 26 Jun 2022 16:51:20 woxex.py[line:29] ERROR Traceback (most recent call last):
  File "C:\Users\Max Lin Worm\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Raindrop\woxex.py", line 45, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Max Lin Worm\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Raindrop\main.py", line 25, in request
    return requests.get(url, params=params, headers=headers)
NameError: name 'requests' is not defined

Sun, 26 Jun 2022 16:51:21 woxex.py[line:29] ERROR Traceback (most recent call last):
  File "C:\Users\Max Lin Worm\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Raindrop\woxex.py", line 45, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Max Lin Worm\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Raindrop\main.py", line 25, in request
    return requests.get(url, params=params, headers=headers)
NameError: name 'requests' is not defined

Sun, 26 Jun 2022 16:51:21 woxex.py[line:29] ERROR Traceback (most recent call last):
  File "C:\Users\Max Lin Worm\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Raindrop\woxex.py", line 45, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Max Lin Worm\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Raindrop\main.py", line 31, in query
    r = self.request('https://api.raindrop.io/rest/v1/raindrops/0', params={
AttributeError: 'NoneType' object has no attribute 'json'

Sun, 26 Jun 2022 16:51:22 woxex.py[line:29] ERROR Traceback (most recent call last):
  File "C:\Users\Max Lin Worm\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Raindrop\woxex.py", line 45, in wrap
    return func(*args, **kwargs)
  File "C:\Users\Max Lin Worm\AppData\Local\Wox\app-1.3.578\Plugins\Wox.Plugin.Raindrop\main.py", line 31, in query
    r = self.request('https://api.raindrop.io/rest/v1/raindrops/0', params={
AttributeError: 'NoneType' object has no attribute 'json'

**Comment by Liu233w** [comment]
Hmmmm I just realise I forgot to mention that you also need to install the dependency: `pip install requests`

Thanks for telling me that.
